-- Placify: Seed 71 common genres
-- Run this in Supabase SQL Editor
-- Safe to re-run (ON CONFLICT DO NOTHING)

INSERT INTO "Genre" (id, slug, name, "createdAt", "updatedAt") VALUES
('g01', 'afrobeat', 'Afrobeat', NOW(), NOW()),
('g02', 'afrobeats', 'Afrobeats', NOW(), NOW()),
('g03', 'amapiano', 'Amapiano', NOW(), NOW()),
('g04', 'dancehall', 'Dancehall', NOW(), NOW()),
('g05', 'hip-hop', 'Hip-Hop', NOW(), NOW()),
('g06', 'house', 'House', NOW(), NOW()),
('g07', 'indie', 'Indie', NOW(), NOW()),
('g08', 'k-pop', 'K-Pop', NOW(), NOW()),
('g09', 'latin', 'Latin', NOW(), NOW()),
('g10', 'lofi', 'Lo-Fi', NOW(), NOW()),
('g11', 'pop', 'Pop', NOW(), NOW()),
('g12', 'r&b', 'R&B', NOW(), NOW()),
('g13', 'reggaeton', 'Reggaeton', NOW(), NOW()),
('g14', 'trap', 'Trap', NOW(), NOW()),
('g15', 'electronic', 'Electronic', NOW(), NOW()),
('g16', 'jazz', 'Jazz', NOW(), NOW()),
('g17', 'soul', 'Soul', NOW(), NOW()),
('g18', 'rock', 'Rock', NOW(), NOW()),
('g19', 'folk', 'Folk', NOW(), NOW()),
('g20', 'edm', 'EDM', NOW(), NOW()),
('g21', 'punk', 'Punk', NOW(), NOW()),
('g22', 'alternative', 'Alternative', NOW(), NOW()),
('g23', 'ambient', 'Ambient', NOW(), NOW()),
('g24', 'bedroom-pop', 'Bedroom Pop', NOW(), NOW()),
('g25', 'blues', 'Blues', NOW(), NOW()),
('g26', 'chill', 'Chill', NOW(), NOW()),
('g27', 'chillhop', 'Chillhop', NOW(), NOW()),
('g28', 'chillwave', 'Chillwave', NOW(), NOW()),
('g29', 'classical', 'Classical', NOW(), NOW()),
('g30', 'country', 'Country', NOW(), NOW()),
('g31', 'dance', 'Dance', NOW(), NOW()),
('g32', 'dark-pop', 'Dark Pop', NOW(), NOW()),
('g33', 'deep-house', 'Deep House', NOW(), NOW()),
('g34', 'dnb', 'DnB', NOW(), NOW()),
('g35', 'downtempo', 'Downtempo', NOW(), NOW()),
('g36', 'dream-pop', 'Dream Pop', NOW(), NOW()),
('g37', 'dubstep', 'Dubstep', NOW(), NOW()),
('g38', 'experimental', 'Experimental', NOW(), NOW()),
('g39', 'funk', 'Funk', NOW(), NOW()),
('g40', 'future-house', 'Future House', NOW(), NOW()),
('g41', 'glitch-pop', 'Glitch Pop', NOW(), NOW()),
('g42', 'hardcore', 'Hardcore', NOW(), NOW()),
('g43', 'hard-rock', 'Hard Rock', NOW(), NOW()),
('g44', 'hyperpop', 'Hyperpop', NOW(), NOW()),
('g45', 'indie-electronic', 'Indie Electronic', NOW(), NOW()),
('g46', 'indie-folk', 'Indie Folk', NOW(), NOW()),
('g47', 'indie-hip-hop', 'Indie Hip Hop', NOW(), NOW()),
('g48', 'indie-pop', 'Indie Pop', NOW(), NOW()),
('g49', 'indie-r&b', 'Indie R&B', NOW(), NOW()),
('g50', 'indie-rock', 'Indie Rock', NOW(), NOW()),
('g51', 'lo-fi', 'Lo-Fi', NOW(), NOW()),
('g52', 'lofi-beats', 'Lofi Beats', NOW(), NOW()),
('g53', 'lounge', 'Lounge', NOW(), NOW()),
('g54', 'melodic-house', 'Melodic House', NOW(), NOW()),
('g55', 'melodic-techno', 'Melodic Techno', NOW(), NOW()),
('g56', 'metal', 'Metal', NOW(), NOW()),
('g57', 'minimal', 'Minimal', NOW(), NOW()),
('g58', 'neo-soul', 'Neo Soul', NOW(), NOW()),
('g59', 'pop-rock', 'Pop Rock', NOW(), NOW()),
('g60', 'post-punk', 'Post-Punk', NOW(), NOW()),
('g61', 'progressive-house', 'Progressive House', NOW(), NOW()),
('g62', 'rap', 'Rap', NOW(), NOW()),
('g63', 'reggae', 'Reggae', NOW(), NOW()),
('g64', 'rnb', 'R&B', NOW(), NOW()),
('g65', 'shoegaze', 'Shoegaze', NOW(), NOW()),
('g66', 'singer-songwriter', 'Singer-Songwriter', NOW(), NOW()),
('g67', 'synth-pop', 'Synth Pop', NOW(), NOW()),
('g68', 'tech-house', 'Tech House', NOW(), NOW()),
('g69', 'techno', 'Techno', NOW(), NOW()),
('g70', 'tropical-house', 'Tropical House', NOW(), NOW()),
('g71', 'world', 'World', NOW(), NOW())
ON CONFLICT (slug) DO NOTHING;

SELECT COUNT(*) as total_genres FROM "Genre";
